@startuml
left to right direction
skinparam linetype ortho

skinparam nodesep 20

actor Carpooler
actor Driver
actor User

Driver --|> User
Carpooler --|> User

rectangle "System" {
usecase "Offer Ride" as UC_offer_ride
usecase "Find Ride" as UC_find_ride
usecase "Arrange Pickup" as UC_arrange_pickup
usecase "Confirm Pickup" as UC_confirm_pickup
usecase "Rate User" as UC_rate_user
usecase "Create Ride" as UC_create_ride
usecase "Join Ride" as UC_join_ride
usecase "Edit Profile" as UC_edit_profile
usecase "Report User" as UC_report_user
usecase "View Past Rides" as UC_view_past_rides
usecase "Redeem Rewards" as UC_redeem_rewards
usecase "Manage Ride" as UC_manage_ride
usecase "Sign In" as UC_sign_in
usecase "Sign Up" as UC_sign_up
'usecase "Forgot Password" as UC_forgot_password
}

Driver --- UC_offer_ride
Driver --- UC_arrange_pickup
Driver --- UC_create_ride
Carpooler --- UC_find_ride
Carpooler --- UC_confirm_pickup
Carpooler --- UC_join_ride

User --- UC_rate_user
User --- UC_edit_profile
User --- UC_report_user
User --- UC_view_past_rides
User --- UC_redeem_rewards
User --- UC_manage_ride
User --- UC_sign_in
User --- UC_sign_up
'User --- UC_forgot_password

UC_sign_in <... UC_sign_up : "<extend>"
'UC_sign_in <... UC_forgot_password : "<extend>"

UC_create_ride <... UC_offer_ride : "<extend>"
UC_join_ride ...> UC_arrange_pickup : "<include>"
UC_arrange_pickup ...> UC_confirm_pickup : "<include>"
UC_find_ride <... UC_join_ride : "<extend>"

@enduml
