@startuml

actor Passenger

participant FindRideView
participant FindRideViewModel
participant RideRepository
participant Navigator
participant LoopApp
participant HomeView
participant Ride
participant RideCard

activate LoopApp
activate FindRideViewModel
activate RideRepository
activate Navigator
activate HomeView


Passenger -> HomeView: Presses "Find Ride"
HomeView -> HomeView: onFindRidePressed()
HomeView -> Navigator: pushNamed("/find-ride")
Navigator -> LoopApp: "/find-ride"
LoopApp -> FindRideView: FindRideView(findRideViewModel)
activate FindRideView
FindRideView -> RideCard: RideCard(ride, onJoinRidePressed: onJoinRidePressed)
activate RideCard
RideCard --> FindRideView: return rideCard
deactivate RideCard
FindRideView --> LoopApp: return findRideView
LoopApp --> Navigator: return findRideView
Navigator --> FindRideView: build(context)

alt Insta Ride
Passenger -> FindRideView: Enters source location
FindRideView -> FindRideView: onSourceLocationChanged()
FindRideView -> FindRideViewModel: selectSourceLocation()
FindRideViewModel -> FindRideViewModel: updateRides()
FindRideViewModel -> RideRepository: fetchMatchingRides(...)
RideRepository -> Ride: Ride(...)
activate Ride
Ride --> RideRepository: return ride
deactivate Ride
RideRepository --> FindRideViewModel: matchingRides
FindRideViewModel -> FindRideViewModel: onRidesUpdated(matchingRides)

FindRideView -> RideCard: RideCard(ride, onJoinRidePressed: onJoinRidePressed)
activate RideCard
RideCard -> FindRideView: return rideCard
deactivate RideCard
Passenger -> FindRideView: Enters destination location
FindRideView -> FindRideView: onDestinationLocationChanged()
FindRideView -> FindRideViewModel: selectDestinationLocation()
FindRideViewModel -> FindRideViewModel: updateRides()
FindRideViewModel -> RideRepository: fetchMatchingRides(...)
deactivate Ride
RideRepository -> Ride: Ride(...)
activate Ride
Ride --> RideRepository: return ride
deactivate Ride
RideRepository --> FindRideViewModel: matchingRides
FindRideViewModel -> FindRideViewModel: onRidesUpdated(matchingRides)

FindRideView -> RideCard: RideCard(ride, onJoinRidePressed: onJoinRidePressed)
activate RideCard
RideCard -> FindRideView: return rideCard
deactivate RideCard

Passenger -> FindRideView: Enters departure time
FindRideView -> FindRideView: onDepartureTimeChanged()
FindRideView -> FindRideViewModel: selectDepartureTime()
FindRideViewModel -> FindRideViewModel: updateRides()
FindRideViewModel -> RideRepository: fetchMatchingRides(...)

RideRepository -> Ride: Ride(...)
activate Ride
Ride --> RideRepository: return ride
deactivate Ride
RideRepository --> FindRideViewModel: matchingRides
FindRideViewModel -> FindRideViewModel: onRidesUpdated(matchingRides)

FindRideView -> RideCard: RideCard(ride, onJoinRidePressed: onJoinRidePressed)
activate RideCard
RideCard -> FindRideView: return rideCard
deactivate RideCard
Passenger -> FindRideView: Enters arrival time
FindRideView -> FindRideView: onArrivalTimeChanged()
FindRideView -> FindRideViewModel: selectArrivalTime()
FindRideViewModel -> FindRideViewModel: updateRides()
FindRideViewModel -> RideRepository: fetchMatchingRides(...)

RideRepository -> Ride: Ride(...)
activate Ride
Ride --> RideRepository: return ride
deactivate Ride
RideRepository --> FindRideViewModel: matchingRides
FindRideViewModel -> FindRideViewModel: onRidesUpdated(matchingRides)

FindRideView -> RideCard: RideCard(ride, onJoinRidePressed: onJoinRidePressed)
activate RideCard
RideCard -> FindRideView: return rideCard
   deactivate RideCard
else Activity Selection
    Passenger -> FindRideView: Presses "Select Activity"
    FindRideView -> FindRideView: onSelectActivityPressed()
    FindRideView -> ActivitySelectionPanel: ActivitySelectionPanel(activities)
    activate ActivitySelectionPanel
    ActivitySelectionPanel -> FindRideView: onActivitySelected(activity)
   
    Passenger -> ActivitySelectionPanel: Selects activity
     deactivate ActivitySelectionPanel
    FindRideView -> FindRideViewModel: selectActivity(activity)

    
    FindRideViewModel -> FindRideViewModel: update form fields (from, to, times)
    FindRideViewModel -> FindRideViewModel: fetchRides()
    FindRideViewModel -> RideRepository: fetchMatchingRides(RideRequest)

    RideRepository --> FindRideViewModel: matchingRides
   
    FindRideViewModel -> FindRideViewModel: onRidesUpdated(matchingRides)
   
  
    FindRideView -> RideCard: RideCard(ride, onJoinRidePressed)
   activate RideCard
    RideCard -> FindRideView: return rideCard
    deactivate RideCard
end

@enduml
