@startuml

actor User

participant SignInView
participant SignInViewModel
participant AuthenticationRepository
participant Navigator
participant ForgotPasswordView
participant ForgotPasswordViewModel
participant LoopApp

activate Navigator
activate LoopApp
activate AuthenticationRepository
activate SignInViewModel
activate ForgotPasswordViewModel

' TODO: async
Navigator --> LoopApp: "/sign-in"

LoopApp -> SignInView: SignInView(signInViewModel)
activate SignInView

== Sign In ==
User -> SignInView: Enters email
User -> SignInView: Enters password
User -> SignInView : Presses "Sign In"
SignInView -> SignInView: onSignInPressed()
SignInView -> SignInViewModel : signIn()
SignInViewModel -> AuthenticationRepository : login(email, password)

alt Success
AuthenticationRepository --> SignInViewModel : authentication
SignInViewModel --> SignInView : ok
SignInView -> Navigator : pushNamed("/home")

else User not found
    AuthenticationRepository --> SignInViewModel : User not found
    SignInViewModel -> SignInViewModel: setErrorMessage("User not found")
    SignInViewModel --> SignInView : failure
    SignInView -> SignInView: showErrorMessage()
else Wrong password
    AuthenticationRepository --> SignInViewModel : Wrong password
    SignInViewModel -> SignInViewModel: setErrorMessage("Wrong password")
    SignInViewModel --> SignInView : failure
    SignInView -> SignInView: showErrorMessage()
end

== Forgot Password ==
User -> SignInView: Presses "Forgot Password?"
SignInView -> SignInView: onForgotPasswordPressed()
SignInView -> Navigator: pushNamed("/forgot-password")
' TODO: async
Navigator -> LoopApp: "/forgot-password"
LoopApp -> ForgotPasswordView: ForgotPasswordView(forgotPasswordViewModel)
activate ForgotPasswordView
User -> ForgotPasswordView: Enters email
User -> ForgotPasswordView: Press "Send Reset Link"
ForgotPasswordView -> ForgotPasswordView: onSendResetLinkPressed()
ForgotPasswordView -> ForgotPasswordViewModel: sendResetLink()
ForgotPasswordViewModel -> AuthenticationRepository: sendResetLink(email)
alt Success
    AuthenticationRepository --> ForgotPasswordViewModel: success
    ForgotPasswordViewModel --> ForgotPasswordView: ok
    User -> ForgotPasswordView: Enters reset code
    ' TODO
else User not found
    AuthenticationRepository --> ForgotPasswordViewModel: User not found
    ForgotPasswordViewModel -> ForgotPasswordViewModel: setErrorMessage("User not found")
    ForgotPasswordViewModel --> ForgotPasswordView: failure
    ForgotPasswordView -> ForgotPasswordView: showErrorMessage()
end

@enduml
