@startuml
skinparam linetype ortho
skinparam nodesep 50

' App
LoopApp ---> SignInView
LoopApp ---> SignUpView
LoopApp ---> ForgotPasswordView
LoopApp ---> SignInViewModel
LoopApp ---> SignUpViewModel
LoopApp ---> ForgotPasswordViewModel
LoopApp ---> HomeView
LoopApp ---> HomeViewModel
LoopApp ---> AuthenticationRepository
LoopApp ---> UserRepository
LoopApp ---> RideRepository
LoopApp ---> RewardRepository
LoopApp ---> ReportUserView
LoopApp ---> UserDetailsView
LoopApp ---> HttpUserRepository
LoopApp ---> CachedUserRepository

' ViewModels
SignInViewModel ---|> ViewModelBase
SignUpViewModel ---|> ViewModelBase
ForgotPasswordViewModel ---|> ViewModelBase
HomeViewModel ---|> ViewModelBase
RewardViewModel ---|> ViewModelBase
ReportUserViewModel ---|> ViewModelBase
UserDetailsViewModel ---|> ViewModelBase

' Views -> ViewModels, Widgets
SignInView ...> SignInViewModel
SignUpView ...> SignUpViewModel
ForgotPasswordView ...> ForgotPasswordViewModel
HomeView ...> HomeViewModel
HomeView ...> MapProvider
RewardView ...> RewardViewModel
ReportUserView ...> ReportUserViewModel
UserDetailsView ...> UserDetailsViewModel

' ViewModels -> Repositories, Models
SignInViewModel ....> AuthenticationRepository
SignInViewModel ...> UserRepository
SignUpViewModel ...> AuthenticationRepository
SignUpViewModel ...> UserRepository
ForgotPasswordViewModel ...> AuthenticationRepository
ForgotPasswordViewModel ...> UserRepository
ReportUserViewModel ...> UserRepository
ReportUserViewModel ...> ReportRepository
UserDetailsViewModel ...> UserRepository
UserDetailsViewModel ...> User
RewardViewModel ...> RewardRepository

' Repositories
AuthenticationRepository ---> AuthenticationToken
UserRepository ---> User
RideRepository ---> Ride
RewardRepository ---> Reward
HttpUserRepository ...|> UserRepository
CachedUserRepository ...|> UserRepository

'Models and misc
JsonWebToken ...|> AuthenticationToken
Reward ---> RewardStatus
ReportRepository ---> Report
User ---> Report
Report ---> User
Report ---> ReportReason
Ride ---> Driver
Ride ---> Passenger
Ride ---> RideParticipant
Ride ---> RideStatus
Passenger ---|> RideParticipant
Driver ---|> RideParticipant
RideParticipant ---|> User
PickupPoint ---|> RoutePoint
DropoffPoint ---|> RoutePoint
RoutePoint ---|> StartPoint
RoutePoint ---|> EndPoint
Route ---> RoutePoint
Route ---> DropoffPoint
Route ---> PickupPoint
Route ---> StartPoint
Route ---> EndPoint
Ride ---> Route
DropoffPoint ---> RidePassenger
PickupPoint ---> RidePassenger
GoogleMapProvider ...|> MapProvider
MapProvider ---> Route
MapProvider ---> RoutePoint
User ---> Rating
Driver ---> Vehicle
Vehicle ---> User
Motorbike ...|> Vehicle
Car ...|> Vehicle

class RewardView {

}

class RewardViewModel {

}

enum RewardStatus {

}

class Motorbike {

}

class Car {

}

class Vehicle {

}

class Route {

}

class StartPoint {

}

class EndPoint {

}


class RoutePoint {

}

class DropoffPoint {

}

class PickupPoint {

}


enum RideStatus {

}

class Passenger {

}

class Driver {

}

class RideParticipant {

}

class UserDetailsViewModel {

}

interface MapProvider {

}

class GoogleMapProvider {

}

enum ReportReason {

}


class ReportRepository {
}

class LoopApp {

}

class ViewModelBase {

}

class ReportUserViewModel {

}

class RideRepository {

}

class SignInView {
    +onSignInClick()
    +onForgotPasswordClick()
    +onSignUpClick()
}

class SignInViewModel {
    +email
    +password
    +signIn()
}

class SignUpView {
    +onSignUpClick()
    +onSignInClick()
}

class SignUpViewModel {
    +name
    +email
    +password
    +confirmPassword
    +signUp()
}

class ForgotPasswordView {
    +email
    +onResetPasswordClick()
}

class ForgotPasswordViewModel {
    +email
    +resetPassword()
}

class HomeView {

}

class HomeViewModel {
}

interface AuthenticationRepository {
    +login()
    +logout()
}

interface UserRepository {
    +createUser()
    +getUser()
    +updateUser()
    +deleteUser()
}

interface AuthenticationToken {

}

class CachedUserRepository {
}

class JsonWebToken {
}

class RideRepository {

}

class RewardRepository {
    +getRewards()
}

class Reward {
    +requiredPoints
    +name
    +description
    +image
    +expirationDate
    +couponCode
}

class UserDetailsView {
    +onRateUserClick()
    +onReportUserClick()
}

class ReportUserView {
    -reasonSelector
    -descriptionField
    -onConfirmClick()
    -onCancelClick()
}

class Rating {
    +stars
    +comment
    +timestamp
}

class Report {
    +from
    +to
    +timestamp
    +reason
    +description
}

class User {
    +id
    +name
    +email
    +password
    +ratings
    +reports
}

class Ride {
}


@enduml
