@startuml
object User {
    id
    name
}

object Driver {
}

Driver --down|> User

object Vehicle {
}

Driver --up Vehicle: "Drives"

object Carpooler {
}

Carpooler --down|> User

object Ride {
    arrivalTime
    destination
}

Carpooler --up Ride: "Wants"

Driver --up Ride: "Offers"

Driver --right[hidden] Carpooler

object Reward {
}

Reward --left Driver: "Receives"

Reward --right Carpooler: "Receives"

object Rating {
    stars
    comment
}

Ride --up[hidden] Rating

Rating -- Driver: "Receives"

Rating -- Carpooler: "Posts"

object Report {
    reason
}

Report --right User: "Files/Receives"

object Pickup {
    location
    time
}

Driver -- Pickup: "Arranges"
Carpooler -- Pickup: "Accepts"

Reward --up[hidden] Ride
Pickup --up[hidden] Reward

object Route {
    roadGraph
}

Driver -- Route: "Makes"

User --up[hidden] Pickup
User --up[hidden] Route

object Location {
    address
    coordinates
}

Location --o Ride
Location --o Pickup
Location --o Route

object Area {
    id
    name
}

Location --* Area

object Activity {

}
User --right Activity: "Creates"

Activity --up Ride: "Requires"

@enduml
