@startuml

actor "User"
actor "Driver"
actor "Parking Space Owner"

"Driver" -up-|> "User"
"Parking Space Owner" -up-|> "User"

left to right direction

rectangle "Parking Subsystem" {
    usecase "Report Parking"
    usecase "Park"
    usecase "Unpark"
    usecase "Find Parking"
    usecase "Register Parking Space"
    usecase "Edit Parking Space"
    usecase "Share Parking Spot"
    usecase "View Parking History"
    usecase "View Saved Parking Spaces"
    usecase "Save Parking Space"
    usecase "Pay for Parking"
    usecase "Find my Car"
}

"User" -- "Report Parking"

"Driver" -- "View Saved Parking Spaces"
"Driver" -- "Save Parking Space"
"Driver" -- "View Parking History"
"Driver" -- "Share Parking Spot"
"Driver" -- "Find Parking"
"Driver" -- "Park"
"Driver" -- "Unpark"
"Driver" -- "Pay for Parking"
"Driver" -- "Find my Car"

"Parking Space Owner" -- "Register Parking Space"
"Parking Space Owner" -- "Edit Parking Space"

"Save Parking Space" .> "Find Parking": <<extend>>
"Pay for Parking" .> "Find Parking": <<extend>>

"Share Parking Spot" .> "Park": <<extend>>
"View Parking History" .> "Park": <<extend>>
"Unpark" .> "Park": <<extend>>

"Register Parking Space" .> "Edit Parking Space": <<include>>

@enduml
