@startuml

actor "User"
actor "Driver"
actor "Carpooler"

"Carpooler" --|> "User"
"Driver" --|> "User"

left to right direction

rectangle "System" {
    usecase "Manage Activities"
    usecase "Create Activity"
    usecase "Edit Activity"

    usecase "Manage Account"
    usecase "View History"
    usecase "View Rating"

    usecase "Rate User"
    usecase "Report User"
    usecase "Redeem Reward"

    usecase "Find Ride"
    usecase "Arrange Pickup"
    usecase "Accept Pickup"
    usecase "Offer Ride"
}

"User" -- "Manage Activities"
"User" -- "Create Activity"
"User" -- "Edit Activity"

"User" -- "Manage Account"
"User" -- "View History"
"User" -- "View Rating"

"User" -- "Rate User"
"User" -- "Report User"
"User" -- "Redeem Reward"


"Manage Activities" <.-left- "Create Activity": "<<extend>>"
"Manage Activities" <.-right- "Edit Activity": "<<extend>>"

"Manage Account" <.-left- "View History": "<<extend>>"
"Manage Account" <.-right- "View Rating": "<<extend>>"

@enduml
