@startuml

actor "User"
actor "Driver"
actor "Parking Space Owner"

"Driver" -up-|> "User"
"Parking Space Owner" -up-|> "User"

left to right direction

rectangle "Parking Subsystem" {
    usecase "Park"
    usecase "Find Parking"
    usecase "Pay for Parking"

    usecase "Manage Account"

    usecase "Manage Parking Spaces"
    usecase "Register Parking Space"
    usecase "Edit Parking Space"
}

"User" -- "Manage Account"

"Driver" -- "Find Parking"
"Driver" -- "Park"
"Driver" -- "Pay for Parking"

"Parking Space Owner" -- "Register Parking Space"
"Parking Space Owner" -- "Edit Parking Space"
"Parking Space Owner" -- "Manage Parking Spaces"

"Find Parking" <.-left- "Park": "<<extend>>"
"Find Parking" <.-right- "Pay for Parking": "<<extend>>"
"Pay for Parking" -right-.> "Park": "<<include>>"

"Manage Parking Spaces" <.-left- "Edit Parking Space": "<<extend>>"
"Manage Parking Spaces" <.-right- "Register Parking Space": "<<extend>>"



@enduml
