@startuml

actor "User"
actor "Driver"
actor "Carpooler"

"Carpooler" --|> "User"
"Driver" --|> "User"

left to right direction

rectangle "Carpooling Subsystem" {
    usecase "Create Activity"
    usecase "Edit Activity"
    usecase "Find Ride"
    usecase "Arrange Pickup"
    usecase "Accept Pickup"
    usecase "Rate Driver"
}

rectangle "Common Subsystem" {
    usecase "Redeem Reward"
    usecase "Edit Profile"
    usecase "Report User"
}

"User" -- "Edit Profile"
"User" -- "Redeem Reward"
"User" -- "Report User"

"User" -- "Create Activity"
"User" -- "Edit Activity"

"Driver" -- "Arrange Pickup"

"Carpooler" -- "Find Ride"
"Carpooler" -- "Accept Pickup"
"Carpooler" -- "Rate Driver"

"Create Activity" .> "Edit Activity": <<include>>
"Edit Activity" .> "Find Ride": <<extend>>
"Accept Pickup" .> "Find Ride": <<extend>>

@enduml
