@startuml

actor "User"
actor "Driver"
actor "Carpooler"

"Carpooler" --|> "User"
"Driver" --|> "User"

left to right direction

rectangle "System" {
    usecase "Create Activity"
    usecase "Manage Activities"
    usecase "Edit Activity"

    usecase "Manage Account"
    usecase "View History"
    usecase "View Rating"

    usecase "Rate User"
    usecase "Report User"
    usecase "Redeem Reward"

    usecase "Find Ride"
    usecase "Arrange Pickup"
    usecase "Accept Pickup"
    usecase "Offer Ride"

    usecase "Manage Ride"
}

"User" -- "Manage Activities"
"User" -- "Create Activity"
"User" -- "Edit Activity"

"User" -- "Manage Account"
"User" -- "View History"
"User" -- "View Rating"

"User" -- "Rate User"
"User" -- "Report User"
"User" -- "Redeem Reward"

"Carpooler" -- "Find Ride"
"Carpooler" -- "Accept Pickup"
"Driver" -- "Arrange Pickup"
"Driver" -- "Offer Ride"

"Find Ride" <.-- "Arrange Pickup": "<<extend>>"

"Manage Activities" <.-left- "Create Activity": "<<extend>>"
"Manage Activities" <.-right- "Edit Activity": "<<extend>>"

"Manage Account" <.-left- "View History": "<<extend>>"
"Manage Account" <.-right- "View Rating": "<<extend>>"

"Arrange Pickup" <. "Accept Pickup": "<<extend>>"

"Offer Ride" .> "Arrange Pickup": "<<include>>"

"Manage Ride" <.-left- "Redeem Reward": "<<extend>>"
"Manage Ride" <.-left- "Report User": "<<extend>>"
"Manage Ride" <.-right- "Rate User": "<<extend>>"

User -- "Manage Ride"

@enduml
