@startuml
left to right direction

object User {
    id
    username
    email
    password
    name
}

object Driver {
}

Driver --|> User

object Carpooler {
}

Carpooler --|> User

object Ride {
    id
    date
    time
    duration
    arrivalTime
    destination
}

object Vehicle {
}

Driver --> Vehicle : "Drives"

Carpooler --> Ride : "Wants"
Driver --> Ride : "Offers"

object RideHistory {
    contents
}

User --> RideHistory : "has"

object Rating {
    stars
    comment
}

User --> Rating : "gives"
Ride --> Rating : "receives"
Rating --> User : "posts/receives"

object Report {
    id
    reason
    description
}

User --> Report : "creates"
Report --> User : "targets"

object ReportArchive {
}

ReportArchive --> Report : "archives"

object Pickup {
    location
    time
}

Driver --> Pickup : "arranges"
Carpooler --> Pickup : "accepts"

object Reward {
}

Reward --> Driver : "receives"
Reward --> Carpooler : "receives"

object Route {
    roadGraph
}

Driver --> Route : "makes"

object Location {
    address
    coordinates
}

Location --o Ride
Location --o Pickup
Location --o Route

object Activity {
}

User --> Activity : "creates"
Activity --> Ride : "requires"

object InstaRide {
}

InstaRide --|> Ride

object ProfilePage {
}

ProfilePage --> User : "displays"

object ReportUserPage {
}

ReportUserPage --> User : "reports"

object PastRidesPage {
}

PastRidesPage --> Ride : "lists"

object RideDetailsPage {
}

RideDetailsPage --> Ride : "details"

object RatingPage {
}

RatingPage --> Rating : "manages"

object PopupMessage {
    message
}

object ConfirmationDialog {
    choices
}

PastRidesPage --> PopupMessage
RideDetailsPage --> PopupMessage
ReportUserPage --> PopupMessage
ProfilePage --> PopupMessage

PastRidesPage --> ConfirmationDialog
RideDetailsPage --> ConfirmationDialog
ReportUserPage --> ConfirmationDialog
ProfilePage --> ConfirmationDialog

object MainPage {

}

object ManageRidePage {

}

object AccountPage {

}

object OfferRidePage {

}

object RewardsPage {

}

object FindRidePage {

}

object PickupDetailsPage {

}

object ActivitiesPage {

}


object Page {

}

MainPage --|> Page
ManageRidePage --|> Page
AccountPage --|> Page
OfferRidePage --|> Page
RewardsPage --|> Page
FindRidePage --|> Page
PickupDetailsPage --|> Page
ActivitiesPage --|> Page
PastRidesPage --|> Page
RideDetailsPage --|> Page
ReportUserPage --|> Page
ProfilePage --|> Page


@enduml
